### ISSUE TITLE
Latest version does not work at all

### ISSUE THREAD

**Issue by SpuriousSnail86** [steamcore/TinyIpc#11]
**Installed latest version and i cant even get the constructor to work anymore. reverted to previous version for the time being**

```
public static void Initialize()
        {
            try
            {
                bus  = new TinyIpc.Messaging.TinyMessageBus(MessageBusName);
                bus.MessageReceived += Bus_MessageReceived;
            }
            catch (Exception ex)
            {
               
            }
        }
```

**above code throws the following exception**

Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at Hscm.IPC.ClientManager.Initialize()
   at Hscm.UI.MainWindow.InitializeCore()
   at Hscm.UI.MainWindow.Initialize()
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by DavidZidar** [comment]
That is too little information, it works fine for me in both .NET Framework and .NET 6.

What file does it fail to load? What .NET version are you running? AnyCPU or x86 or x64?

**Comment by SpuriousSnail86** [comment]
The code snippet I showed above is literally what causes the exception to be thrown. The Initialize method shown above gets called by another class to create the IPC connection, presumably with a MMF (Memory Mapped File).

Sadly , the exception does not give any further detail.

I don't think it's a physical file. Its an MMF most likely.
It just looks like its failing to create the MMF. MessageBusName is a constant: "HSC.MessageBus".

The .NET Framework ver is 4.8 and its a 64 bit CPU - Ryzen 9 3900x, but the project build setting is set for Any CPU.

**Comment by DavidZidar** [comment]
I doubt it, my code isn't even in the stacktrace. It's probably some assembly that is failing to load. You will have to look that up in the exception properties in a debugger to find out which one.

**Comment by DavidZidar** [comment]
Since I can't help without knowing more I'm closing this issue.
